### ISSUE TITLE
The HUM tokens are shown in imToken1 but not in imToken2.

### ISSUE THREAD

**Issue by devmasme** [consenlabs/token-profile#379]
The HUM tokens are shown in imToken1 but not in imToken2. What do I need to do in order for it to show up in the imToken2 app?

**Comment by wenyanwang** [comment]
Hello,

Currently, imToken has been released 2.0 version. We will support display more token information, including token price, ICO price, and your project's profile, so that to make users know your project clearly and need you to submit information to imToken github https://github.com/consenlabs/token-profile/

For tutorials, please refer to: https://github.com/consenlabs/token-profile/blob/master/README.md

We will deal with your request as soon as possible. If you have any questions, please communicate with us in Github.
