### ISSUE TITLE
Old Contract information delete

### ISSUE THREAD

**Issue by Expertstudent** [consenlabs/token-profile#5389]
*Hello please remove information token *from old contract : 0xa1f18ba7a1fa1f2c15eae5c42e722278f1235b7a
*For information migration : https://cn.etherscan.com/token/0xa1f18ba7a1fa1f2c15eae5c42e722278f1235b7a
*we have received reports that someone has sold (old) tokens to other users

**Comment by sfsy520** [comment]
In imToken 1.0, if duplicated token names are found, imToken team will add a number after the token name for the project, like TFT1, TFT2 etc. If you wish to remove the number, we need to claim, this is a very dangerous operation. Removing the number is not advisable, as amending the token name will cause the token to disappear from imToken display and may cause unnecessary panic among users. For tokens with many holders, we recommend the token project to suggest to your users, to download and use imToken 2.0, as imToken 2.0 distinguish tokens via contract address. Therefore, this mitigates the problem of duplicated token names.
If there are update requests due to contract amendment, follow the checklist:
1. make an official announcement for the upgrade of the contract
2. submit a new PR in GitHub:
    * desaturate the old logo (In Photoshop: image - adjustments - desaturate)
    * resubmit new token contract’s json and logo
3. share your announcement link under the comment section in the PR
